---
title: "Endividamento dos Municipios"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    Horizontal_layout: fill
    theme:
      bootswatch: morph
runtime: shiny
---

```{r setup, include=FALSE, warning=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(readxl)
library(sf)
library(tmap)
library(tmaptools)
library(leaflet)
library(viridis) #pacote de palhetas
library(DT)
library(magrittr)
library(stringr)
```


```{r funções, echo=FALSE}
format_real <- function(values, nsmall = 0) {
  values %>%
    as.numeric() %>%
    format(nsmall = nsmall, decimal.mark = ",", big.mark = ".") %>%
    str_trim() %>%
    str_c("R$ ", .)
}
```


```{r dados, results='hide'}
#importando dados
capag <- read_xlsx("capag.xlsx", sheet = 1)
capag1 <- capag
capag1$Endividamento <- round(capag1$`Endividamento%pib`, digits = 4)
capag1$Poupança <- round(capag1$Poupança_Corrente, digits = 4)
capag1$Liquidez <- round(capag1$Liquidez, digits = 4)
capag1 <- capag1[,-c(2,3,4,5,6,7,8,10,11,12)]

capag2 <- capag
capag2 <- capag2[,-c(2,3,4,5,6,7,8,9,10)]
capag2 <- capag2 %>%
    mutate(Limite = case_when(Nota_CAPAG == "A" ~ RCL*0.12, 
                                 Nota_CAPAG == "B" ~ RCL*0.08,
                                 Nota_CAPAG == "C" ~ RCL*0.03))

capag2$RCL <- format_real(capag2$RCL, 2)
capag2$Limite <- format_real(capag2$Limite, 2)

mymap <- geobr::read_municipality(code_muni = c("RS", "SC"), year = 2020, showProgress = FALSE)

#mapa temático
tmap_mode("view")
mymap <- as.data.frame(mymap)
mapa_and_data <- inner_join(mymap,capag, by = "code_muni")
mapa_and_data <- st_as_sf(mapa_and_data) #Transforamdo em 'formato especial'
```


Column {.sidebar data-width=200}
=====================================

INFORME:

Desenvolvido para visualização da capacidade de pagamento dos municípios.


Visão Geral{data-icon="fa-signal"}
=====================================



Column {data-width=600}
-----------------------------------------------------------------------

### Distribuição das Notas CAPAGs pelos municípios

```{r}
tm_shape(mapa_and_data) +
  tm_basemap(leaflet::providers$OpenStreetMap) +
  tm_fill("Nota_CAPAG", id = "name_muni", palette = "viridis", 
          popup.vars = c("População", "Endividamento%pib", "Poupança_Corrente", "Liquidez", "Nota_CAPAG"), 
          alpha = 0.4) + tm_borders() + tm_scale_bar()
```

Column {data-width=450}
-----------------------------------------------------------------------

### Indicadores municipais

```{r}
DT::renderDT(
  capag1 %>%
    DT::datatable(options = list(
    pageLength = 5
)))
```

### Limite de financiamento

```{r}
DT::renderDT(
  capag2 %>%
    DT::datatable(options = list(
    pageLength = 5
)))
```

